env:
  - ANSIBLE_VERSION='ansible>=2.5,<2.6'
  - ANSIBLE_VERSION='ansible>=2.6,<2.7'
  - ANSIBLE_VERSION='ansible>=2.7,<2.8'

language: python

install:
  - pip install "$ANSIBLE_VERSION"

script:
  - ansible-playbook --syntax-check tests/test.yml

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
